[[redirects]]
  from = "/.well-known/lnurlp/jose"
  to = "/functions/redirect-to-lightning"
  status = 200

[[redirects]]
  from = "/functions/redirect-to-lightning"
  to = "https://lightning.josemoranurena.tech/.well-known/lnurlp/jose"
  status = 200
  force = true
