[[redirects]]
  from = "/"
  to = "https://haunt.gg/jmuofficial"
  status = 301

[[redirects]]
  from = "/bills/*"
  to = "/bills/*.html"
  status = 200

[[redirects]]
  from = "/resume"
  to = "/resume.pdf"
  status = 200
