name: R2 Backup
on:
  push:
    branches:
      - main
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: R2 Backup
        uses: JoseMoranUrena523/r2-backup@r2-backup
        env:
          ACCESS_KEY_ID: '203484521b5920bbcbc7fc7f02f19491'
          BUCKET_NAME: 'personal-website-storage'
          SECRET_ACCESS_KEY: 'eb51e23c3a3036faa0fef68aaf081d5b988c3295c590ba0fe0fa7a1ecd311899'
          ACCOUNT_ID: '7c8d6e10d82240531424fe08f321556c'
        with:
          args: --overwrite --remove
